### ISSUE TITLE
Support Offline Servers

### ISSUE THREAD

**Issue by orkun1675** [WorldCretornica/PlotMe-Core#127]
When you have time can you also add support for offline servers?
I believe the only issue is with UUID's, I could help with the coding if thats the case?

Thanks!

**Comment by ZachBora** [comment]
Offline mode is not supported because there is no way to know the user is who he says he is with matching UUID.

The only way we would add support is if there was a way, by contacting Mojang, to get a reply that says "yes that player is on that server". There is a mojang API where you send mojang the username and server id but I do not see how to get the server id, I don't think it's exposed, but if you know how to get that in NMS or CB we could work with that.

Sidenote: there is no valid reason to have a server in offline mode unless you want to allow hacked clients, which we do not support. Auth plugin? Still doesn't prove it's your account. There is no way to prove it unless what I wrote above, contacting mojang.

UUID works with Lilypad and online Bungeecord.

**Comment by ZachBora** [comment]
Found the mojang API thing.

>This link seems to be called when a server with online-mode=true checks if it should allow a player to join the game. The session ID is generated by the launcher when you log in (you can also generate them with the "getversion.jsp" link above). The server ID is the server's identity. This URL will return "OK" if the given session ID is the last one to have been generated for that username; otherwise it will return "Bad login".
```
http://session.minecraft.net/game/checkserver.jsp?user=<USERNAME>&serverId=<SERVER ID>
```

I just haven't been able to get the serverId. Bukkit does not expose it. I think it's like Bukkit.getServerId() and it's an empty string.

**Comment by MattBDev** [comment]
@ZachBora that is not something we are able to get from a server. Bukkit does not expose it and so far, I don't think Sponge does either.

**Comment by orkun1675** [comment]
Bungee validates the player. So we don't have to worry about security and contacting Mojang.

Using the method getUniqueId() will be sufficient?

I am new to the BukkitAPI though.

**Comment by MattBDev** [comment]
@orkun1675 Bungee passes the UUID and Name to the Bukkit and Spigot servers and the server is technically is in an online state. Although your issue may be fixed, many people have requested for real offline support so they can use the plugin even without bungeecord

**Comment by orkun1675** [comment]
Ok. So you will be basically looking for player names only for offline mode right? The UUID is md5 hash only.

**Comment by ZachBora** [comment]
@orkun1675 If the player.getuniqueid() is the real UUID then plotme should be working fine, I believe Matt said Bungee is supposed to put the correct uuid in the player.

If the uuid in the player is wrong (aka md5 of the username), we can't be sure it was validated with Mojang.

**Comment by orkun1675** [comment]
So we shouldn't care if it is validated with Mojang, to support offline mode servers. Just let them pass through by looking at their names.

**Comment by ZachBora** [comment]
@orkun1675 We aren't blocking offline mode servers, we are just taking their UUID. If it doesn't match they were not validated. We don't support illegal servers.

**Comment by GreatGBL** [comment]
@ZachBora 
Enn, the reason of unsupporting offline is could not match correct UUID ?
I have an idea ,use Authme for register each player's name in the server. so each plot can correct match each player.

Can I do that ? I promise,I DO NOT sell any VIP or game's items .It is free server ,In my country , over 90% players haven't got genuine account , In the other word , they play offline server . If I had established online server , I would have had lonely server which has 1 player ,It is me . :(
I really like Minecraft and really want to organize my players to building or enjoy in this game,Although offline server has a lot of player who spam,steaI and practical joke , I keep my server(NO VIP) for half past 1 years ago .

**Comment by MattBDev** [comment]
@GreatGBL I am not sure why you keep mentioning the selling of items to players? This has nothing to do with this issue.
A "cracked" server is also referred to an offline server and usually supports users that are using a version of the game that they did not legally obtain. Due to this reason, they can choose any name they like and will not have a Mojang UUID. Their UUID will be based upon their username, so if they decide to change the name their UUID changes.
We do not support the user of cracked clients and refuse to do so. If we did implement some form of offline support, we would need to constantly keep calling mojang servers. Eventually servers would be blocked by mojang for reaching the UUID fetch limit.
Unless someone has a valid reason for being offline or someone has a solution that does not rely on a 3rd Party plugin, offline mode is not supported.

**Comment by GreatGBL** [comment]
@MattBDev 
Well,I have a lot of experience about offline server . Now my server's version is 1.7.2 which hasn't got UUID system,players can choose any name they want ,I use Auhtme plugin for mangage each player's name .
Therefore , I was establisbed a acidisland server Last month in 1.7.10.  I found everplayers has got his particular UUID , so I can speculation, offline has his separate mechanism about UUID .

I just want to know why are you unsupport the offline , your copyright ,Mojang's benfit or could not match correct UUID ?  If the problem is technical problems (UUID) , I would solve by myself . If the issues about your copyrigh ,I wouldn't use your plugins  :)

**Comment by orkun1675** [comment]
My only wish is that you don't disallow PlotMe for servers that run in offline (cracked) mode. I know this is  very easy to do in the technical side. And using player names instead of UUIDS if the server is offline doesn't flag PlotMe as an 'illegal plugin'.

I kindly ask you re-consider this issue. If you could point me in the direction of the methods causing this issue (I couldn't locate them myself) I could try and push a commit that fixes them myself.

**Comment by MattBDev** [comment]
The only troublesome method is the getUniqueId method that gets the uuid of the player. If a server is in offline mode, this is will be calculated based upon the username of the player. Since it is based on the username, every time a user changes their name they will get a brand new UUID.
We don't block users from using the plugin in offline mode. There is nothing in the code that prevents the running of it.

@ZachBora and I do not approve of the use of cracked clients. In fact, cracked users do not have a Mojang UUID. Their UUID is based the same way I described above.
Using a 3rd party plugin is not a valid solution to allow offline clients since there is still the risk of someone stealing someone else's builds. We technically can't offer offline support because BukkitDev will ban us if we do.

**Comment by GreatGBL** [comment]
@MattBDev 
@orkun1675 

Thx for your help , I will solue the technical problems of UUID by myself ,and thanks for your great work .

**Comment by GreatGBL** [comment]
@ZachBora  
@MattBDev 
@orkun1675 

Good news , After a heated discussion by me and OP, I will establish ONLINE server ,less players is not important,is it ?
Could you talk me your used names in minecraft ? I just want to build 3 your's statue for commemoration in my server .

**Comment by GreatGBL** [comment]
@ZachBora  
@MattBDev 
@orkun1675 

Thx for your help and great work , I will establish online server , less players is not important , is it ?

**Comment by MattBDev** [comment]
@MarkusAV is now discussion mediator.

**Comment by MarkusAV** [comment]
I don't believe this discussion/issue needs further attention as it's allready determined that PlotMe will not support offline servers.

**Comment by MattBDev** [comment]
MARKUS HAS SPOKEN!!!!

**Comment by MarkusAV** [comment]
I will now return to my :goat:

**Comment by orkun1675** [comment]
@MattBDev taking your word for it I installed 0.16.3 on a live server. But during startup, when converting player names to UUIDS, PlotMe started deleting records in my database stating "Name not found at mojang". For the plugin to work on offline servers also, PlotMe should not delete players which it assign a UUID, but rather assign these users an offline (md5 hash) UUID.

During player checks, if the player UUID cannot be fetched from mojang, a hash version should again be used. I would modify these places in the source code, if I could understand the complexity of your plugin. But I couldn't...

@MarkusAV could you help me with this please?

**Comment by MattBDev** [comment]
@orkun1675 > We technically can't offer offline support because BukkitDev will ban us if we do
