### ISSUE TITLE
[Idea] Clear plot when claimed

### ISSUE THREAD

**Issue by PrisonHeist** [WorldCretornica/PlotMe-Core#176]
When a user claims a plot it gets automatically cleared first

**Comment by MattBDev** [comment]
No, because this defeats the purpose of having the plot dispose command.

**Comment by PrisonHeist** [comment]
Can it be an option for the config? as I have quite a few plots with no owners now that should, I don't expire plots so must have been during UUID conversion. I would like when people get new plots that they don't already have tons of items on them.

**Comment by EvilOlaf** [comment]
Usually you don't have a problem like this more than one time, because as you wrote the situation happened under some circumstances at UUID conversion. So it seem you have to just look around and clear all unused plots by hand.
If you have users that can build on any plot ( -> plotme.admin.buildanywhere) you may tell them to claim these plots before building to mark them used.

**Comment by PrisonHeist** [comment]
Thank you Olaf, I will claim them all until it looks how it should.
