### ISSUE TITLE
plot world destroy

### ISSUE THREAD

**Issue by diegoandonie99** [WorldCretornica/PlotMe-Core#195]
the players can build on their plots but they can destroy, what is the permission to aloud them to destroy

**Comment by MattBDev** [comment]
Please use better grammar and spelling next time because your comment said "they can build on their plots but they CAN destroy". There is no permission to stop them from building or breaking blocks on their own plot. If they are trying to place blocks on their plot from the road it is a bug at the moment. Make sure you have any other plugins that may be interfering disabled in plotworld.

**Comment by diegoandonie99** [comment]
they cant destroy

**Comment by MattBDev** [comment]
I already explained that there is no specific permission to build and destroy on your own plot. Make sure you don't have spawn protection enabled. Also make sure no other plugins are conflicting. This is not a bug, this is a issue to you specifically. Do not report something here unless you know it is a bug.
