### ISSUE TITLE
Number of plots being generated

### ISSUE THREAD

**Issue by garyharry** [WorldCretornica/PlotMe-Core#210]
Hey
I'm pretty new to minecraft servers.  Just installed the plotme plugin and changed the PlotAutoLimit to 50.  However I'm still getting very large amounts of plots being generated.  Also for some reason I have a Default-Generator folder for the plugin which as a separate config file.

Sorry if this as been answered a million times but I have been googling for sometime and haven't found any information.  Is there a set minim number of plots needed?

**Comment by EvilOlaf** [comment]
You just did not understand what PlotAutoLimit does.
This variable has NOTHING to do with world generation.

PlotAutoLimit limits the number of plots which can be claimed with the plot auto command. If more than X plots already have been claimed and someone tries to use /plot auto the command will notify the player that no free plots have been found and ask an admin to manually give the player a plot.
So the default value of 1000 is pretty good because it is a good balance between enough room for auto claiming and lag.

If you want to limit the world size of your plot world use a 3rd party plugin like WorldBorder.

**Comment by garyharry** [comment]
Thanks for the reply.  I'm sorry I am guilty of not reading the configuration plotme core information.  I just read it :/ 

Is World Border easy to setup?

**Comment by EvilOlaf** [comment]
I think so. Just read the documentation and use Google  and you'll be fine.

**Comment by jomo** [comment]
@EvilOlaf 
> You just did not understand what PlotAutoLimit does.

:sunglasses:

PlotAutoLimit **limits the radius** in which unclaimed plots are **searched** with the plot auto command.
I'm quite sure about that.

**Comment by MarkusAV** [comment]
Minecraft worlds are acctually limited to 30,000,000 blocks :stuck_out_tongue: 
This is the description of PlotAutoLimit: "The maximum number of plots to check starting at spawn until a free plot is found."

**Comment by jomo** [comment]
±30M (in all 4 directions), IIRC

**Comment by jomo** [comment]
I took a quick look into the code and what it *actually* does is starting at plot `0;0` (not necessarily spawn) and then searches up to `plotAutoLimit²` plots for an unclaimed one.

It seems to be searching in all directions, I think it may be doing it in a (squared-)spiral strategy, at least there was some recent discussion about doing that.

**Comment by MattBDev** [comment]
@jomo I recently changed that. It does a check at 0;0 in a spiral.

**Comment by EvilOlaf** [comment]
Maybe I had to add the information that PlotMe searching from the middle. Thought that was obvious.
