### ISSUE TITLE
Still not solved...

### ISSUE THREAD

**Issue by danieltabrizian** [WorldCretornica/PlotMe-Core#257]
How to initiate the API class? in your plugin it just gets it from the main class, how do i do this externally? since the methods in the api are not static....

**Comment by MattBDev** [comment]
They are not supposed to be static. Do what the plugin does:
`PlotMeCoreManager.getInstance()` and then assign it to a variable then you just need to call upon the methods you need. Please do not open another issue regarding the api or it will be closed automatically. If you have more questions, ask them on issue number #237 instead of opening another issue. Opening another issue is very annoying.
