### ISSUE TITLE
Plot creation date on plot info

### ISSUE THREAD

**Issue by Weeksy113** [WorldCretornica/PlotMe-Core#261]
I would like it if the info displayed on a plot could contain the date it was created.

**Comment by MattBDev** [comment]
If this was added, it wouldn't be to tell when existing plots before this addition were created. I'll leave it up to the other users to make the decision to add this.

**Comment by TALLPUP** [comment]
I have always wanted plotme to show the date it was created in the Plotme Info. First (& mainly) It would be a useful tool when evaluating a half build plots whether they been there for a week or several months. Second, since 99.98% of our players have their original plots, it would help give some indication when they started.

**Comment by MattBDev** [comment]
@TALLPUP If this was added, the existing plots would not have accurate information on when they were created. The date of when the plot was created would be the day the plugin was updated. The creation date of the plot is not stored anywhere in the current version of PlotMe

**Comment by MarkusAV** [comment]
This sounds really good to me actually!

**Comment by frizzbee30** [comment]
If I recall your already looking at the owner info popping up when entering a plot? Thats the only real feature we would be after  :)

**Comment by camstib** [comment]
This would be great! I come from a server where this would really useful.

**Comment by MattBDev** [comment]
Accepted
