### ISSUE TITLE
No PlotMe Folder!

### ISSUE THREAD

**Issue by tinlonchiu** [WorldCretornica/PlotMe-Core#266]
Spigot 1.7.10
PlotMe:0.16.3
Pastebin:http://pastebin.com/UeV8BwUP

**Comment by MattBDev** [comment]
You have a broken jar. Try reading your log files before reporting issues.

**Comment by tinlonchiu** [comment]
How do I fix this? I kept redeleting it and it never works

**Comment by EvilOlaf** [comment]
Redownload the plugin from official source and replace the broken one.

**Comment by MattBDev** [comment]
No, he has a broken server jar. The only way to resolve your issue is to upgrade to 1.8.3

**Comment by MarkusAV** [comment]
http://www.spigotmc.org/wiki/spigot-installation/
Depending on you having a server host or not and if that host supports daemon jars, but this is what you'd do if your host don't have predefined jars:
1. Download BuildTools from https://hub.spigotmc.org/jenkins/job/BuildTools/
2. Run BuildTools (depending on what OS you have), google for help or see spigot wiki
3. You should now have a Spigot.jar , replace that with your broken jar

It is highly recommended to upgrade to 1.8.3, since the next release of PlotMe will be built for 1.8.3
