### ISSUE TITLE
Creating Plotworlds With Multiverse Doesn't Work! Please Help!

### ISSUE THREAD

**Issue by LTchewybar** [WorldCretornica/PlotMe-Core#268]
I have been try to do /mv create plotworld normal -g PlotMe but it just says "Invalid generator! 'PlotMe'. Aborting world creation". I've searched through the config to find the cause of it put nope can't find anything Please Help!!

**Comment by SomewhatDisoriented** [comment]
The generator is now named 'PlotMe-DefaultGenerator' instead of just 'PlotMe'.

The wiki explains everything step-by-step, I recommend that you read it. :smile:
Fresh install: http://worldcretornica.github.io/PlotMe-Core/setup.html
Upgrading from PlotMe 0.13: http://worldcretornica.github.io/PlotMe-Core/upgrading.html
