### ISSUE TITLE
PlotMe UUID's instead of Playernames!

### ISSUE THREAD

**Issue by xAcrosonicx** [WorldCretornica/PlotMe-Core#291]
Since players have been able to change their names, I have some people (player W) who take the name of X player who changed his name to Y. So, player W changes their name to X, so they have access to plots that had the original X as a plot helper. Would it be possible for the plotme plugin to use unique UUID's to prevent this?

**Comment by MattBDev** [comment]
Plotme already uses UUID's. Your database must be corrupted.

**Comment by xAcrosonicx** [comment]
How am I suppose to fix this? I didn't change anything and am not sure how this would happen.

**Comment by MattBDev** [comment]
Unfixable.

**Comment by xAcrosonicx** [comment]
I have worked with many many plugin developers, and I must say, you are one of the rudest, and least helpful I have ever encountered. You are so short, quick to close tickets, and have no intent to help it seems. I will not be recommending your plugins.

**Comment by MattBDev** [comment]
@xAcrosonicx There is nothing I can do to fix the database. I have had several reports of corrupt databases and I have used several tools to try to fix them. I can't help fix an issue I have already tried (and failed) to fix in the past. Not following the guidelines for submitting makes me upset since they are not only listed on the page before you submit but they are also here on github. It looks like you were very late to upgrade from plotme 0.13 (I am going to assume 0.13b since you are having troubles with UUID's) to 0.16.3 . I can't be held responsible since 0.13f was released in last May (a year ago) and 0.15.X was available since December. I help as much as I can where I can, if you don't like that then fine.

**Comment by xAcrosonicx** [comment]
Never saw any guidelines for submitting, all that there was was a green button that says new issue. Trust me, I am 100% for following guidelines when submitting/reporting an issue. I am just telling you this so that you will (hopefully) change and not be short, quick to close, or seemingly unhelpful, it will really turn people away. I suggest you look into this problem more, for you have had several reports on it, and I can tell you from experience, it is awful to have this issue.

**Comment by MattBDev** [comment]
@xAcrosonicx SQL is extremely difficult to work with and once there is corruption it is almost impossible to remove it. The issue with corruption with plotme databases (which only occurs with SQLite databases) is that the corruption isn't able to be seen and it isn't able to be modified due to how deep in the code it is. I have spent a significant amount of time looking into this (not joking. I have spent about 3 days worth of time on this) and I will not be spending any more. Try downloading an Database viewer tool and look in your database. You will see no signs of corruption because it isn't able to be detected. I am already rewriting all the SQL code so if corruption is still possible in the newest version, it will be fixed in the next version. If you still really want me to try to fix this you can try uploading your database to dropbox or something and sharing it with me.

**Comment by xAcrosonicx** [comment]
The odd part is, I never used MySQL, and I appreciate your offer to look into it. I will upload my DataBase, but it was the one saved in the PlotMe file itself, maybe the issue is different from the ones you've worked on. 
Here it is: http://pastebin.com/xV9KSnwL

**Comment by MattBDev** [comment]
@xAcrosonicx I need the actual database file. Putting that in pastebin is just a bunch of gibberish that I can't do anything with. I suggest uploading the file to Dropbox, OneDrive, or Google drive and giving me a link to the file I can download.

**Comment by xAcrosonicx** [comment]
I'll share it via Google Drive, what's your email?

**Comment by MattBDev** [comment]
Just post the link here.

**Comment by xAcrosonicx** [comment]
https://drive.google.com/file/d/0ByfwvQeim6pxa0hpcnhGbU9JVEk/view?usp=sharing

**Comment by MattBDev** [comment]
@xAcrosonicx Did google drive do anything to the file? It keeps telling me the file format is incorrect which could only mean something happened to the file (such as corruption)

**Comment by xAcrosonicx** [comment]
I am unaware of anything it would have done. Want to add me on skype and I can send it over

**Comment by MattBDev** [comment]
Give me your skype name and I will add you. It will be easier to communicate that way too.

**Comment by xAcrosonicx** [comment]
Jakepetersen011@gmail.com
