### ISSUE TITLE
Plotme donelist not working

### ISSUE THREAD

**Issue by Binary3** [WorldCretornica/PlotMe-Core#324]
Sorry for reposting this, but it was closed on account of .17 not working on 1.7 minecraft. I get that :P My issue is that the /plot donelist isn't working on my .16.4 version, running on 1.7 minecraft. As far as I know that should work. 

Here is the original issue post:
Hey :)
When players do /plot done, their plot isn't added to the plot donelist. Instead doing /plot donelist only returns the message "No plots are finished".
I also can't find the command on your commandlist anymore (http://plotme.worldcretornica.com/cmdsandperms), is this intentional? Or a known issue? Or is it just me having this issue?

// Binary3

**Comment by MattBDev** [comment]
I have updated PlotMe from 0.16 to 0.17 . During this update, I have decided to stop supporting Minecraft 1.7 . I have already fixed this for 0.17 which contains bug fixes for 0.16 . Resubmitting this does nothing because I fixed the bug. It is super easy to upgrade to Minecraft 1.8 and Spigot has offered it since November last year.
