### ISSUE TITLE
Internal error with command aliases when with mcMMO

### ISSUE THREAD

**Issue by Conzine** [WorldCretornica/PlotMe-Core#328]
/p on my server is supposed to be enabling party chat, a feature part of the mcMMO plugin.  Now when they type it it try to output plotme help.  So I disabled plotme permissions in the main part of the server and just tried allowing them to have the perms on the creative/plot world.  Well even when they don't have permissions for the plugin it says the internal error message.

Craftbukkit version: git-spigot-(mc:1.8.7-R0-1)
plotme version: 0.17.4

**Comment by Conzine** [comment]
Im proposing a way to disable the 2 aliases that you have in the plugin in the confirmation (/p, /plot) as it messes with another plugin of mine.  Otherwise I'll have to look for a new plugin.

Thank you.

**Comment by Conzine** [comment]
Just found another issue with end portals.  It won't teleport people through them, but people can toss items into them and they spawn on the actual end portal.  I'm removing this plugin because I don't know what other exploits it may have.

**Comment by MarkusAV** [comment]
Please edit your comment rather than making more comments, and make new issues for multiple issues.

1. I've discovered that most of the plugin users use the /p command rather than /plot or /plotme, so it will not be removed.., but what you can do for a fix is changing the alias of command "p" in the commands.yml file in your server root to the mcMMO plugins party chat command.. if I'm not wrong it also has an alias "partychat", and if not this should work "mcmmo:p".

2. I'll report this to Matt, but please open a new issue about it so we can go from there.
If you still decided to give up on PlotMe, I am sorry.

**Comment by MattBDev** [comment]
@Conzine Portals usually don't work in worlds other than your default world. I can't really fix that.
