### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by barthasaurus** [WorldCretornica/PlotMe-Core#93]
hey! I used your latest version for my minecraft server and it has mods. It says that has an internal server. But I tried using your 1.7.9 version on the bukkit website and it works perfectly except for the world edit. Do you have any idea on how to fix this? Im using Tekkit version 1.2.9e on mcprohosting.

**Comment by MarkusAV** [comment]
Pastebin the error

**Comment by barthasaurus** [comment]
11.01 22:10:53 [Server] INFO ... 13 more
11.01 22:10:53 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.207]
11.01 22:10:53 [Server] INFO at com.worldcretornica.plotme_core.bukkit.BukkitCommand.onCommand(BukkitCommand.java:105) ~[?:?]
11.01 22:10:53 [Server] INFO at com.worldcretornica.plotme_core.commands.CmdShowHelp.exec(CmdShowHelp.java:145) ~[?:?]
11.01 22:10:53 [Server] INFO at com.worldcretornica.plotme_core.PlotMeCoreManager.getFirstWorld(PlotMeCoreManager.java:318) ~[?:?]
11.01 22:10:53 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
11.01 22:10:53 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_55]
11.01 22:10:53 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
11.01 22:10:53 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
11.01 22:10:53 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
11.01 22:10:53 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
11.01 22:10:53 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
11.01 22:10:53 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
11.01 22:10:53 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
11.01 22:10:53 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
11.01 22:10:53 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1130) [nh.class:?]
11.01 22:10:53 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1348) [nh.class:?]
11.01 22:10:53 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.207]
11.01 22:10:53 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.207]
11.01 22:10:53 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.207]
11.01 22:10:53 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'plot' in plugin PlotMe v0.15.2
11.01 22:10:53 [Server] ERROR null

**Comment by barthasaurus** [comment]
Thats what it says when I do /plot

**Comment by MarkusAV** [comment]
Next time either use Pastebin or markdown
You gotta use an older version of PlotMe (0.13b) available at dev.bukkit.org/bukkit-plugins/plotme/
Can't tell if you're using an online or offline mode server.., PlotMe 0.13f> only supports Online Mode. PlotMe 0.15.x is built for Spigot/Craftbukkit 1.8 and has not been tested on modded servers

**Comment by Dignition** [comment]
13.01 21:41:41 [Server] INFO ... 14 more
13.01 21:41:41 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-e497721-96d09e3]
13.01 21:41:41 [Server] INFO at com.worldcretornica.plotme_core.bukkit.BukkitCommand.onCommand(BukkitCommand.java:105) ~[?:?]
13.01 21:41:41 [Server] INFO at com.worldcretornica.plotme_core.commands.CmdShowHelp.exec(CmdShowHelp.java:145) ~[?:?]
13.01 21:41:41 [Server] INFO at com.worldcretornica.plotme_core.PlotMeCoreManager.getFirstWorld(PlotMeCoreManager.java:318) ~[?:?]
13.01 21:41:41 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
13.01 21:41:41 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
13.01 21:41:41 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-e497721-96d09e3]
13.01 21:41:41 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-e497721-96d09e3]
13.01 21:41:41 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-e497721-96d09e3]
13.01 21:41:41 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot.jar:git-Spigot-e497721-96d09e3]
13.01 21:41:41 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_72]
13.01 21:41:41 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_72]
13.01 21:41:41 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-e497721-96d09e3]
13.01 21:41:41 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-e497721-96d09e3]
13.01 21:41:41 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-e497721-96d09e3]
13.01 21:41:41 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot.jar:git-Spigot-e497721-96d09e3]
13.01 21:41:41 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot.jar:git-Spigot-e497721-96d09e3]
13.01 21:41:41 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-e497721-96d09e3]
13.01 21:41:41 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-e497721-96d09e3]
13.01 21:41:41 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-e497721-96d09e3]
13.01 21:41:41 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'plot' in plugin PlotMe v0.15.2
13.01 21:41:41 [Server] ERROR null

**Comment by Dignition** [comment]
Then "internal server error" up

**Comment by EvilOlaf** [comment]
What did you do when the error occoured?
What version of Bukkit are you running?
What about using Markdown or Pastebin?

Different cause? Might have nothing to do with the topic issue.

**Comment by MarkusAV** [comment]
Posting an error is not the only thing to do when you have a problem. How did you get that error? Is your configs correct(are the plotworlds in lowercase)? Are you on Bukkit/Spigot 1.8? Are you running an online mode or offline mode server?... etc.
